name: 京东每日签到

on:
  workflow_dispatch:
  schedule:
    - cron: '45 0 * * *'
  #watch:
  #  types: started
  #repository_dispatch:
  #  types: bean_sgin
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      URL: "https://raw.githubusercontent.com/jiegto/Actions_JX/master/jd_bean_sign.js"
      RUNFILE: "jd_bean_sign.js"
      JD_COOKIE: ${{ secrets.JD_COOKIE }}
      JD_DEBUG: ${{ secrets.JD_DEBUG }}
      JD_BEAN_STOP: ${{secrets.JD_BEAN_STOP}} #自定义延迟签到,单位毫秒. 默认分批并发无延迟. 延迟作用于每个签到接口, 如填入延迟则切换顺序签到(耗时较长)
      JD_BEAN_SIGN_STOP_NOTIFY: ${{secrets.JD_BEAN_SIGN_STOP_NOTIFY}}
      JD_BEAN_SIGN_NOTIFY_SIMPLE: ${{secrets.JD_BEAN_SIGN_NOTIFY_SIMPLE}}
      PUSH_KEY: ${{ secrets.PUSH_KEY }}
      BARK_PUSH: ${{ secrets.BARK_PUSH }}
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
      TG_USER_ID: ${{ secrets.TG_USER_ID }}
      BARK_SOUND: ${{ secrets.BARK_SOUND }}
      DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
      DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
      IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        #with:
        #  repository: lxk0301/scripts
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        if: env.JD_COOKIE
        run: |
          npm install
      - name: '运行 【京豆每日签到】'
        if: env.JD_COOKIE
        run: |
          node actions.js
